# User configuration location: C:\Users\Bob\AppData\Local\clangd\config.yaml
# [Configuration](https://clangd.llvm.org/config.html#files)

If:
  PathMatch: .*.cpp
CompileFlags:
  Compiler: x86_64-w64-mingw32-g++
  Add:
    - -D__CLANG_MAX_ALIGN_T_DEFINED
    - -Wno-vla-extension
    - -IC:/ProgramData/mingw64/mingw64/lib/gcc/x86_64-w64-mingw32/15.2.0/include
    - -IC:/ProgramData/mingw64/mingw64/lib/gcc/x86_64-w64-mingw32/15.2.0/include/c++
    - -IC:/ProgramData/mingw64/mingw64/lib/gcc/x86_64-w64-mingw32/15.2.0/include/c++/x86_64-w64-mingw32
    - -IC:/ProgramData/mingw64/mingw64/x86_64-w64-mingw32/include
    - -DLOCAL
    - -Wall
    - -Wpedantic
    - -Weffc++
    - -O2
    - -Wextra
    - -Wshadow
    - -Wconversion
    - -Wfloat-equal
    - -Wno-unused-const-variable
    - -Wno-sign-conversion
    - -std=c++20
Index:
  Background: Skip
